import java.util.Random;
import java.util.Scanner;

public class NumberGuessingGameImproved {
    public static void main(String[] args){
        /*
         * We are making a number guessing game
         * For this -
         *   Create a random object
         *   Take user input
         *   You have to guess the number
         *   The prog will calculate number of
         *       attempts it took for you to guess the number
         *       Set a min and max number
         *
         * */

//        Generate random object
        Random rand = new Random();
//        Taking user input
        Scanner scan =new Scanner(System.in);

//        Declare the variable
        int guess;
        int attempts = 0;
        int min = 1;
        int max = 100;
        int randomNumber = rand.nextInt(min, max + 1); // here 1 is included and 11 is excluded

//         Welcome text
        System.out.println("Number Guessing Game");
        System.out.printf("Guess a number between %d to %d:\n", min , max); // using %d to output min and max

//        The loop to guess the number. - this is a do while loop
//        Meaning do this code once while this condition remains true.
        do{
            System.out.println("Enter a guess: ");
            guess = scan.nextInt();
            attempts++;
            if(guess < randomNumber){
                System.out.println("Too Low! Try again.");
            }
            else if(guess > randomNumber){
                System.out.println("Too High! Try again.");
            }
            else{
                System.out.println("You have guessed the correct number which is "+ randomNumber);
                System.out.println("Number of attempts: "+ attempts);
            }
        }
        while(guess != randomNumber);
        // we will keep on playing this game till
        // does not equal the random number generated by computer




        scan.close();
    }
}
