import java.util.Random;
import java.util.Scanner;

public class numberGuessingGame {
    public static void main(String[] args){

        /*
        * We are making a number guessing game
        * For this -
        *   Create a random object
        *   Take user input
        *   You have to guess the number
        *   The prog will calculate number of
        *       attempts it took for you to guess the number
        *
        * */

//        Generate random object
        Random rand = new Random();
//        Taking user input
        Scanner scan =new Scanner(System.in);

//        Declare the variable
        int guess;
        int attempts = 0;
        int randomNumber = rand.nextInt(1, 11); // here 1 is included and 11 is excluded

//         Welcome text
        System.out.println("Number Guessing Game");
        System.out.println("Guess a number between 1 to 10: ");

//        The loop to guess the number. - this is a do while loop
//        Meaning do this code once while this condition remains true.
        do{
            System.out.println("Enter a guess: ");
            guess = scan.nextInt();
            attempts++;
            if(guess < randomNumber){
                System.out.println("Too Low! Try again.");
            }
            else if(guess > randomNumber){
                System.out.println("Too High! Try again.");
            }
            else{
                System.out.println("You have guessed the correct number which is "+ randomNumber);
                System.out.println("Number of attempts: "+ attempts);
            }
        }
        while(guess != randomNumber);
            // we will keep on playing this game till
            // does not equal the random number generated by computer











        scan.close();

    }
}
